export const SOCKET_EVENTS = {
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  CHAT_USER: 'chat:user',
  JOIN_ROOM: 'chat:join_room',
  SEND_MESSAGE: 'chat:send_message',
  RECEIVE_MESSAGE: 'chat:receive_message',
  GET_USER_CHATS: 'chat:get_user_chats',
  USER_CHATS: 'chat:user_chats',
  MARK_READ: 'chat:mark_read',
  UNREAD_UPDATE: 'chat:unread_update',
  ONLINE_USER: 'chat:online_user',
  OFFLINE_USER: 'chat:offline_user',
  USER_STATUS: 'chat:user_status',
  DEAL_CLOUSER: 'chat:deal_clouser',
  DEAL_APPROVAL: 'chat:deal_approval',
  DEAL_STATUS_UPDATE: 'chat:deal_status_update',
  PENDING_DEAL: 'chat:pending_deal',
  PRODUCT_SOLD: 'chat:product_sold',
  DEAL_RATING: 'chat:deal_rating',
};
